### Read the first HIV related websites file (positive class1)

In [2]:
import json

pos_class_list1 = []
with open("pos_class.jsonl") as json_file:
   for line in json_file:
    pos_class_list1.append(json.loads(line))

In [3]:
import pandas as pd

# Create a dataframe from the pos_class_list1: pos_sites1
pos_sites1= pd.DataFrame(pos_class_list1)
pos_sites1.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  
0  Skip to main content En Fr Pt HOME | ABOUT | C...  
1  Register \r\n                                 ...  
2  Skip to Main Content PEPFAR Seal The United St...  
3  Home AIDS 2016 About Staff Office Addresses Co...  
4  facebook twitter linkedin youtube Home Who We ...

In [4]:
# Add a label column of 1s indicating that the sites are HIV related sites
pos_sites1["HIV_related"]=1
pos_sites1.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  HIV_related  
0  Skip to main content En Fr Pt HOME | ABOUT | C...            1  
1  Register \r\n                                 ...            1  
2  Skip to Main Content PEPFAR Seal The United St...            1  
3  Home AIDS 2016 About Staff Office Addresses Co...            1  
4  facebook twitter linkedin youtube Home Who We ...            1

### Read the first NOT HIV related sites folder (Negative Class1)

In [5]:
neg_sites1=pd.read_json("neg_class.jsonl", lines=True)
neg_sites1.head()

domain  \
0          https://stackoverflow.com   
1           https://en.wikipedia.org   
2  https://www.farming-simulator.com   
3              https://www.canva.com   
4                  https://hello.com   

                                           text_dump  
0  Stack Overflow Questions Developer Jobs Tags U...  
1  Cat From Wikipedia, the free encyclopedia \n\t...  
2  Updates Support Australia (en) Belgien (de) Be...  
3   +1 335  Tweet 714  Share 8.5K  Pin 28.4K  Sha...  
4  about us inspiration graphic novel best of hel...

In [6]:
# Add a label column of 0s indicating the sites are NOT HIV related sites
neg_sites1["HIV_related"]=0
neg_sites1.head()

domain  \
0          https://stackoverflow.com   
1           https://en.wikipedia.org   
2  https://www.farming-simulator.com   
3              https://www.canva.com   
4                  https://hello.com   

                                           text_dump  HIV_related  
0  Stack Overflow Questions Developer Jobs Tags U...            0  
1  Cat From Wikipedia, the free encyclopedia \n\t...            0  
2  Updates Support Australia (en) Belgien (de) Be...            0  
3   +1 335  Tweet 714  Share 8.5K  Pin 28.4K  Sha...            0  
4  about us inspiration graphic novel best of hel...            0

## Read the second HIV related sites folder (Positive Class 2)

In [7]:
# Load JSON: json_data
import json

pos_class_list2 = []
with open("pos_class1.jsonl") as json_file:
   for line in json_file:
    pos_class_list2.append(json.loads(line))

In [8]:
pos_sites2=pd.DataFrame(pos_class_list2)
pos_sites2.head()

domain  \
0          https://www.pepfar.gov   
1  https://www.viivhealthcare.com   
2                http://hivsa.com   
3            https://www.ghfp.net   
4     http://www.dapp-namibia.org   

                                           text_dump  
0  Skip to Main Content PEPFAR Seal The United St...  
1  JavaScript is disabled.Please enable to contin...  
2  facebook twitter linkedin youtube Home Who We ...  
3  Jump to navigation Toggle navigation  SIGN IN ...  
4  Register \r\n                                 ...

In [9]:
# Add a label column of 1s indicating the sites are HIV related sites
pos_sites2["HIV_related"]=1
pos_sites2.head()

domain  \
0          https://www.pepfar.gov   
1  https://www.viivhealthcare.com   
2                http://hivsa.com   
3            https://www.ghfp.net   
4     http://www.dapp-namibia.org   

                                           text_dump  HIV_related  
0  Skip to Main Content PEPFAR Seal The United St...            1  
1  JavaScript is disabled.Please enable to contin...            1  
2  facebook twitter linkedin youtube Home Who We ...            1  
3  Jump to navigation Toggle navigation  SIGN IN ...            1  
4  Register \r\n                                 ...            1

### Read the second NOT HIV related sites folder (Negative Class2)

In [10]:
# Load JSON: json_data
import json

neg_class_list2 = []
with open("neg_class1.jsonl") as json_file:
   for line in json_file:
    neg_class_list2.append(json.loads(line))

In [11]:
neg_sites2=pd.DataFrame(neg_class_list2)
neg_sites2.head()

domain  \
0                  https://hello.com   
1  https://www.farming-simulator.com   
2             https://www.random.org   
3                https://storify.com   
4          https://stackoverflow.com   

                                           text_dump  
0  about us inspiration graphic novel best of hel...  
1  Updates Support Australia (en) Belgien (de) Be...  
2  Home Games Lottery Quick Pick Keno Quick Pick ...  
3  Browse Log In Storify Update We appreciate tho...  
4  Stack Overflow Questions Developer Jobs Tags U...

In [12]:
# Add a label column of 0s indicating the sites are NOT HIV related sites
neg_sites2["HIV_related"]=0
neg_sites2.head()

domain  \
0                  https://hello.com   
1  https://www.farming-simulator.com   
2             https://www.random.org   
3                https://storify.com   
4          https://stackoverflow.com   

                                           text_dump  HIV_related  
0  about us inspiration graphic novel best of hel...            0  
1  Updates Support Australia (en) Belgien (de) Be...            0  
2  Home Games Lottery Quick Pick Keno Quick Pick ...            0  
3  Browse Log In Storify Update We appreciate tho...            0  
4  Stack Overflow Questions Developer Jobs Tags U...            0

### Merge all the dataframes which were loaded

In [13]:
# Merge the negative and the positive class dataframes by append() method
sites= pos_sites1.append(neg_sites1).append(pos_sites2).append(neg_sites2)

# Reset the index 
sites.reset_index(drop=True, inplace=True)
sites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 3 columns):
domain         67 non-null object
text_dump      67 non-null object
HIV_related    67 non-null int64
dtypes: int64(1), object(2)
memory usage: 1.6+ KB


In [14]:
sites.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  HIV_related  
0  Skip to main content En Fr Pt HOME | ABOUT | C...            1  
1  Register \r\n                                 ...            1  
2  Skip to Main Content PEPFAR Seal The United St...            1  
3  Home AIDS 2016 About Staff Office Addresses Co...            1  
4  facebook twitter linkedin youtube Home Who We ...            1

## Preprocess the Text Data

- Remove **non-alphabetic** characters,
- **Remove stop words** 
- **Lemmatize**

## Lemmatizer for CountVectorizer
Create a Lemmatizer object to pass in the Sklearn Countvectorizer as `tokenizer` argument

In [15]:
# Import the necessary nltk modules 
from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer 

# Create the LemmaTokenizer Object in order to pass in CountVectorizer
class LemmaTokenizer(object):
    # Initilize WordNetLemmatizer in the class
    def __init__(self):
        self.lemmatizer = WordNetLemmatizer()
        
    def __call__(self, doc):
        # Tokenize the doc: token_list
        tokens_list=word_tokenize(doc)
        
        # Create a list that iterates through tokens_list and retains only alphabetical characters
        # Use the .isalpha() method to check if the character is alphabetical
        alpha_token_list= [token for token in tokens_list if token.isalpha()]
        
        # Return the list after iterating over alpha_tokens_list and lemmatize each token
        return [self.lemmatizer.lemmatize(t) for t in alpha_token_list]

In [28]:
# Import the necessary modules
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [18]:
# Initialize a CountVectorizer object: count_vectorizer
# Specify the argument stop_words="english" so that stop words are removed
# Pass in LemmaTokenizer() as an argument
count_vectorizer = CountVectorizer(stop_words='english', tokenizer=LemmaTokenizer())

In [19]:
# See the outcome of count_vectorizer on a simple data
sample= count_vectorizer.fit_transform(["WheatheR, better apples but i don't like part-2, calculation, calculaters, 21"])
sample_df= pd.DataFrame(sample.toarray(), columns=count_vectorizer.get_feature_names())
sample_df

apple  better  calculaters  calculation  like  wheather
0      1       1            1            1     1         1

In [21]:
# Create a Series to store the labels: y
y = sites.HIV_related
#print(y.head(), "\n")

# Create X (features dataset)
X= sites.text_dump
#print(X.head())

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=73)

In [24]:
# Fit and transform the training data using only X_train ('text_dump' column values): train_dtm
# Create train document-term-matrix by using the .fit_transform() method
train_dtm = count_vectorizer.fit_transform(X_train)
train_dtm

<50x8266 sparse matrix of type '<class 'numpy.int64'>'
	with 16383 stored elements in Compressed Sparse Row format>

In [25]:
# convert sparse matrix to a dense matrix
train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
# Examine the vocabulary and document-term matrix together
doc_term_df= pd.DataFrame(train_dtm.toarray(), columns=count_vectorizer.get_feature_names())
doc_term_df.head()

aafp  aardwolf  abalone  abandonment  abap  abarth  abbreviated  abby  abc  \
0     0         0        0            0     0       0            0     0    0   
1     0         0        0            0     0       0            0     0    0   
2     0         0        0            0     0       3            0     0    0   
3     0         0        0            0     0       0            0     0    0   
4     0         0        0            0     0       0            0     0    0   

   aberration  ...    吴语  文言  日本語  简体中文  粵語  贛語  ꮳꮃꭹ  한국어  ｍｓ  ｐゴシック  
0           0  ...     0   0    0     0   0   0    0    0   0      0  
1           0  ...     0   0    0     0   0   0    0    0   0      0  
2           0  ...     0   0    0     0   0   0    0    0   0      0  
3           0  ...     0   0    0     0   0   0    0    0   0      0  
4           0  ...     0   0    0     0   0   0    0    0   0      0  

[5 rows x 8266 columns]

In [31]:
# Transform the test data (X_test) ie create test document-term-matrix: test_dtm 
# Use ONLY the .transform() method, NOT fit method
test_dtm = count_vectorizer.transform(X_test)

In [32]:
# Print the first 1000 features of the count_vectorizer
# using .get_feature_names() method
print(count_vectorizer.get_feature_names()[:1000])

['aafp', 'aardwolf', 'abalone', 'abandonment', 'abap', 'abarth', 'abbreviated', 'abby', 'abc', 'aberration', 'abidjan', 'abigail', 'ability', 'able', 'abnormality', 'abril', 'absence', 'absinth', 'absolute', 'absolutely', 'absorption', 'abstract', 'abu', 'abuelo', 'abundance', 'abuse', 'abusing', 'abusive', 'abyssinian', 'abyssinica', 'academia', 'academy', 'accelerate', 'accelerating', 'accelerator', 'accelerometer', 'accent', 'acceptability', 'acceptable', 'access', 'accessed', 'accessibility', 'accessing', 'accident', 'accompanied', 'accomplish', 'accordance', 'according', 'account', 'accountability', 'accountable', 'accredited', 'accrued', 'accueil', 'accuracy', 'accurate', 'accurately', 'accused', 'ace', 'acenta', 'acetyl', 'achap', 'acharya', 'achieve', 'acid', 'acinonyx', 'acknowledgement', 'acne', 'acquire', 'acquiring', 'acre', 'acrobat', 'act', 'acta', 'actinidia', 'action', 'active', 'actively', 'activer', 'activist', 'activity', 'actually', 'acute', 'ad', 'adam', 'adaptable

In [33]:
# Import MultinomialNB from sklearn.naive_bayes
from sklearn.naive_bayes import MultinomialNB
# Import the metrics module from sklearn 
from sklearn import metrics

# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training document term matrix
nb_classifier.fit(train_dtm, y_train)

# Compute the predicted tags for the test_data: pred
pred = nb_classifier.predict(test_dtm)
pred

array([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [36]:
# Calculate the accuracy score for the classifier: score
score = metrics.accuracy_score(y_test, pred)
print(score)

0.9411764705882353


In [38]:
# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(nb_classifier, train_dtm, y_train, cv=5)

# Print the 5-fold cross-validation scores
cv_scores

array([0.7, 0.8, 0.8, 0.8, 0.8])

In [39]:
# Print the confusion matrix
confusion_matrix(y_test, pred)

array([[ 5,  0],
       [ 1, 11]], dtype=int64)

In [40]:
# Print the site contents for the false positives (Irrelevant sites incorrectly classified as HIV related)
X_test[y_test < pred]

Series([], Name: text_dump, dtype: object)

In [41]:
# Print the site contents for the false negatives (HIV related sites incorrectly classified as Irrelevant)
X_test[y_test > pred]

37    For full functionality of this site it is nece...
Name: text_dump, dtype: object

In [42]:
# Calculate predicted probabilities for X_test (poorly calibrated)
y_pred_prob = nb_classifier.predict_proba(test_dtm)[:, 1]
y_pred_prob

array([2.78361356e-043, 3.02807761e-255, 1.00000000e+000, 1.03268215e-111,
       1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 8.38096543e-083, 4.02415896e-049,
       1.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000])

In [43]:
# Calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

1.0

In [44]:
print(nb_classifier.coef_)

[[-9.79484388 -9.79484388 -9.79484388 ... -9.79484388 -9.79484388
  -9.79484388]]


## Instantiate a Pipline


In [46]:
# Import pipeline
from sklearn.pipeline import Pipeline

# Create the token pattern in order to include only alpha characters: TOKENS_ALPHA_ONLY 
TOKENS_ALPHA_ONLY = '[A-Za-z]+(?=\\s+)'

# Instantiate Pipeline object: pl
# Add the 'CountVectorizer' step (with the name 'vec') to the correct position in the pipeline
pl = Pipeline([
               ('vec', CountVectorizer(stop_words='english', tokenizer=LemmaTokenizer())),
               ('clf', MultinomialNB())
    ])

# Fit the Pipeline to the training data
pl.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('vec', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        s...78>,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])