### Read the first HIV related websites file (positive class1)

In [30]:
import json

pos_class_list1 = []
with open("pos_class.jsonl") as json_file:
   for line in json_file:
    pos_class_list1.append(json.loads(line))

In [31]:
import pandas as pd

# Create a dataframe from the pos_class_list1: pos_sites1
pos_sites1= pd.DataFrame(pos_class_list1)
pos_sites1.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  
0  Skip to main content En Fr Pt HOME | ABOUT | C...  
1  Register \r\n                                 ...  
2  Skip to Main Content PEPFAR Seal The United St...  
3  Home AIDS 2016 About Staff Office Addresses Co...  
4  facebook twitter linkedin youtube Home Who We ...

In [32]:
# Add a label column of 1s indicating that the sites are HIV related sites
pos_sites1["HIV_related"]=1
pos_sites1.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  HIV_related  
0  Skip to main content En Fr Pt HOME | ABOUT | C...            1  
1  Register \r\n                                 ...            1  
2  Skip to Main Content PEPFAR Seal The United St...            1  
3  Home AIDS 2016 About Staff Office Addresses Co...            1  
4  facebook twitter linkedin youtube Home Who We ...            1

### Read the first NOT HIV related sites folder (Negative Class1)

In [44]:
neg_sites1=pd.read_json("neg_class.jsonl", lines=True)
neg_sites1.head()

domain  \
0          https://stackoverflow.com   
1           https://en.wikipedia.org   
2  https://www.farming-simulator.com   
3              https://www.canva.com   
4                  https://hello.com   

                                           text_dump  
0  Stack Overflow Questions Developer Jobs Tags U...  
1  Cat From Wikipedia, the free encyclopedia \n\t...  
2  Updates Support Australia (en) Belgien (de) Be...  
3   +1 335  Tweet 714  Share 8.5K  Pin 28.4K  Sha...  
4  about us inspiration graphic novel best of hel...

In [45]:
# Add a label column of 0s indicating the sites are NOT HIV related sites
neg_sites1["HIV_related"]=0
neg_sites1.head()

domain  \
0          https://stackoverflow.com   
1           https://en.wikipedia.org   
2  https://www.farming-simulator.com   
3              https://www.canva.com   
4                  https://hello.com   

                                           text_dump  HIV_related  
0  Stack Overflow Questions Developer Jobs Tags U...            0  
1  Cat From Wikipedia, the free encyclopedia \n\t...            0  
2  Updates Support Australia (en) Belgien (de) Be...            0  
3   +1 335  Tweet 714  Share 8.5K  Pin 28.4K  Sha...            0  
4  about us inspiration graphic novel best of hel...            0

## Read the second HIV related sites folder (Positive Class 2)

In [36]:
# Load JSON: json_data
import json

pos_class_list2 = []
with open("pos_class1.jsonl") as json_file:
   for line in json_file:
    pos_class_list2.append(json.loads(line))

In [37]:
pos_sites2=pd.DataFrame(pos_class_list2)
pos_sites2.head()

domain  \
0          https://www.pepfar.gov   
1  https://www.viivhealthcare.com   
2                http://hivsa.com   
3            https://www.ghfp.net   
4     http://www.dapp-namibia.org   

                                           text_dump  
0  Skip to Main Content PEPFAR Seal The United St...  
1  JavaScript is disabled.Please enable to contin...  
2  facebook twitter linkedin youtube Home Who We ...  
3  Jump to navigation Toggle navigation  SIGN IN ...  
4  Register \r\n                                 ...

In [50]:
# Add a label column of 1s indicating the sites are HIV related sites
pos_sites2["HIV_related"]=1
pos_sites2.head()

domain  \
0          https://www.pepfar.gov   
1  https://www.viivhealthcare.com   
2                http://hivsa.com   
3            https://www.ghfp.net   
4     http://www.dapp-namibia.org   

                                           text_dump  HIV_related  
0  Skip to Main Content PEPFAR Seal The United St...            1  
1  JavaScript is disabled.Please enable to contin...            1  
2  facebook twitter linkedin youtube Home Who We ...            1  
3  Jump to navigation Toggle navigation  SIGN IN ...            1  
4  Register \r\n                                 ...            1

### Read the second NOT HIV related sites folder (Negative Class2)

In [39]:
# Load JSON: json_data
import json

neg_class_list2 = []
with open("neg_class1.jsonl") as json_file:
   for line in json_file:
    neg_class_list2.append(json.loads(line))

In [40]:
neg_sites2=pd.DataFrame(neg_class_list2)
neg_sites2.head()

domain  \
0                  https://hello.com   
1  https://www.farming-simulator.com   
2             https://www.random.org   
3                https://storify.com   
4          https://stackoverflow.com   

                                           text_dump  
0  about us inspiration graphic novel best of hel...  
1  Updates Support Australia (en) Belgien (de) Be...  
2  Home Games Lottery Quick Pick Keno Quick Pick ...  
3  Browse Log In Storify Update We appreciate tho...  
4  Stack Overflow Questions Developer Jobs Tags U...

In [46]:
# Add a label column of 0s indicating the sites are NOT HIV related sites
neg_sites2["HIV_related"]=0
neg_sites2.head()

domain  \
0                  https://hello.com   
1  https://www.farming-simulator.com   
2             https://www.random.org   
3                https://storify.com   
4          https://stackoverflow.com   

                                           text_dump  HIV_related  
0  about us inspiration graphic novel best of hel...            0  
1  Updates Support Australia (en) Belgien (de) Be...            0  
2  Home Games Lottery Quick Pick Keno Quick Pick ...            0  
3  Browse Log In Storify Update We appreciate tho...            0  
4  Stack Overflow Questions Developer Jobs Tags U...            0

### Merge all the dataframes which were loaded

In [51]:
# Merge the negative and the positive class dataframes by append() method
sites= pos_sites1.append(neg_sites1).append(pos_sites2).append(neg_sites2)

# Reset the index 
sites.reset_index(drop=True, inplace=True)
sites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 3 columns):
domain         67 non-null object
text_dump      67 non-null object
HIV_related    67 non-null int64
dtypes: int64(1), object(2)
memory usage: 1.6+ KB


In [53]:
sites.head()

domain  \
0  http://www.hivsharespace.net   
1   http://www.dapp-namibia.org   
2        https://www.pepfar.gov   
3         http://www.arasa.info   
4              http://hivsa.com   

                                           text_dump  HIV_related  
0  Skip to main content En Fr Pt HOME | ABOUT | C...            1  
1  Register \r\n                                 ...            1  
2  Skip to Main Content PEPFAR Seal The United St...            1  
3  Home AIDS 2016 About Staff Office Addresses Co...            1  
4  facebook twitter linkedin youtube Home Who We ...            1

## Preprocess the Text Data

- Remove **non-alphabetic** characters,
- **Remove stop words** 
- **Lemmatize**

In [55]:
# Import the necessary modules
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

# Create a Series to store the labels: y
y = sites.HIV_related
#print(y.head(), "\n")

# Create X (features dataset)
X= sites.text_dump
#print(X.head())

In [56]:
# Create training and test sets
# Use a test_size of 0.33 and a random_state of 5
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=5)

In [ ]:
# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(reg, X, y, cv=5)

# Print the 5-fold cross-validation scores
cv_scores

In [57]:
# Create the token pattern in order to include only alphabethical characters: TOKENS_ALPHA_ONLY 
TOKENS_ALPHA_ONLY = '[A-Za-z]+(?=\\s+)'

# Initialize a CountVectorizer object: count_vectorizer
# Specify the argument stop_words="english" so that stop words are removed
# token_pattern=TOKENS_ALPHA_ONLY
count_vectorizer = CountVectorizer(stop_words='english', token_pattern=TOKENS_ALPHA_ONLY, ngram_range=(1, 2))

In [58]:
# See the outcome of count_vectorizer on a simple data
sample= count_vectorizer.fit_transform(["Wheather is GReat today but i don't like part-2"])
sample_df= pd.DataFrame(sample.toarray(), columns=count_vectorizer.get_feature_names())
sample_df

great  great today  like  t  t like  today  today t  wheather  \
0      1            1     1  1       1      1        1         1   

   wheather great  
0               1

In [60]:
# Fit and transform the training data using only X_train ('text_dump' column values): train_dtm
# Create train document term matrix by using the .fit_transform() method
train_dtm = count_vectorizer.fit_transform(X_train)
train_dtm

<44x32160 sparse matrix of type '<class 'numpy.int64'>'
	with 43103 stored elements in Compressed Sparse Row format>

In [61]:
# convert sparse matrix to a dense matrix
train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
# Examine the vocabulary and document-term matrix together
doc_term_df= pd.DataFrame(train_dtm.toarray(), columns=count_vectorizer.get_feature_names())
doc_term_df.head()

aafp  aafp feline  aardwolf  aardwolf cristatus  aaroki  aaroki votes  \
0     0            0         0                   0       0             0   
1     0            0         0                   0       0             0   
2     0            0         0                   0       0             0   
3     0            0         0                   0       0             0   
4     0            0         0                   0       0             0   

   abalone  abalone centre  abalone console  abalones    ...     \
0        0               0                0         0    ...      
1        0               0                0         0    ...      
2        0               0                0         0    ...      
3        0               0                0         0    ...      
4        0               0                0         0    ...      

   zoonosis cats  zoonosis registries  zoonotic  zoonotic canadian  zorro  \
0              0                    0         0                  0      0   
1              0                    0         0                  0      0   
2              0                    0         0                  0      0   
3              0                    0         0                  0      0   
4              0                    0         0                  0      0   

   zorro remaining  zs  zs vincze  zsq  zsq days  
0                0   0          0    0         0  
1                0   0          0    0         0  
2                0   0          0    0         0  
3                0   0          0    0         0  
4                0   0          0    0         0  

[5 rows x 32160 columns]

In [65]:
# Transform the test data X_test. Create test document term matrix: test_dtm 
# Use ONLY the .transform() method, NOT fit method
test_dtm = count_vectorizer.transform(X_test)

In [66]:
# Print the first 1000 features of the count_vectorizer
# using .get_feature_names() method
print(count_vectorizer.get_feature_names()[:1000])

['aafp', 'aafp feline', 'aardwolf', 'aardwolf cristatus', 'aaroki', 'aaroki votes', 'abalone', 'abalone centre', 'abalone console', 'abalones', 'abalones abalone', 'abalones dominators', 'abandonment', 'abandonment household', 'abap', 'abap asked', 'abarth', 'abarth alfa', 'abarth spider', 'abbreviated', 'abbreviated make', 'abby', 'abby ellin', 'abc', 'abc look', 'abc news', 'abcarian', 'abcarian h', 'abe', 'abe parent', 'aberration', 'aberration needed', 'abigail', 'abigail lion', 'ability', 'ability cat', 'ability cats', 'ability characteristic', 'ability create', 'ability digest', 'ability distinguish', 'ability glands', 'ability hunt', 'ability synthesize', 'ability taste', 'ability thrive', 'ability undergo', 'able', 'able authenticate', 'able devote', 'able generally', 'able tolerate', 'abnormalities', 'abnormalities accompanied', 'abril', 'abril archived', 'absence', 'absence mainland', 'absinth', 'absinth items', 'absinth ritifs', 'absolute', 'absolute excellence', 'absolute m

In [67]:
# Import MultinomialNB from sklearn.naive_bayes
from sklearn.naive_bayes import MultinomialNB
# Import the metrics module from sklearn 
from sklearn import metrics

# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training document term matrix
nb_classifier.fit(train_dtm, y_train)

# Compute the predicted tags for the test_data: pred
pred = nb_classifier.predict(test_dtm)
pred

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1], dtype=int64)

In [68]:
# Calculate the accuracy score for the classifier: score
score = metrics.accuracy_score(y_test, pred)
print(score)

0.9565217391304348


In [69]:
# Print the confusion matrix
confusion_matrix(y_test, pred)

array([[10,  1],
       [ 0, 12]], dtype=int64)

In [70]:
# Print the site contents for the false positives (Irrelevant sites incorrectly classified as HIV related)
X_test[y_test < pred]

55    About Companies People YC Continuity Startup S...
Name: text_dump, dtype: object

In [71]:
# Print the site contents for the false negatives (HIV related sites incorrectly classified as Irrelevant)
X_test[y_test > pred]

Series([], Name: text_dump, dtype: object)

In [72]:
# Calculate predicted probabilities for X_test (poorly calibrated)
y_pred_prob = nb_classifier.predict_proba(test_dtm)[:, 1]
y_pred_prob

array([1.00000000e+000, 1.75320483e-006, 1.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 2.11489935e-116, 1.00000000e+000, 1.00000000e+000,
       6.67592586e-032, 1.00000000e+000, 1.00000000e+000, 9.99898277e-001,
       6.15826498e-007, 9.32855734e-015, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 2.10318452e-073, 3.53416039e-173, 4.38788582e-009,
       1.00000000e+000, 5.09687377e-045, 1.00000000e+000])

In [73]:
# Calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

1.0

In [74]:
print(nb_classifier.coef_)

[[-10.81685401 -10.81685401 -10.81685401 ... -10.81685401 -10.12370683
  -10.12370683]]


## Instantiate a Pipline


In [78]:
# Import pipeline
from sklearn.pipeline import Pipeline

# Create the token pattern in order to include only alpha characters: TOKENS_ALPHA_ONLY 
TOKENS_ALPHA_ONLY = '[A-Za-z]+(?=\\s+)'

# Instantiate Pipeline object: pl
# Add the 'CountVectorizer' step (with the name 'vec') to the correct position in the pipeline
pl = Pipeline([
               ('vec', CountVectorizer(stop_words='english', token_pattern=TOKENS_ALPHA_ONLY, ngram_range=(1, 2))),
               ('clf', MultinomialNB())
    ])

# Fit the Pipeline to the training data
pl.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('vec', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='[A-Za-z]+(?=\\s+)',
        tokenizer=None, vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])